sudo: false
language: go

deploy:
  provider: releases
  api_key:
    secure: "tIXqObytNN1qX39mmgJK8rAWzKk3sQk1cJ/qsBCU6WXlbWxGsz4+4XxJLaWb6ewiPjF6HrR9DvjWwAUWBemi0avrU9tPP/6hr0t3h3pf1UxjXceSTUmX9eSOK4LCsp6rR1mAUUjNrpSadN6ooL+Z0cwUhZKQHn6CjOP3jWxWHWc3/BYp2fjD4+mW9wqB6bCqpzGbuvG1rGIYVyJB6dWlLsZy/6mGUxoHwURTl+wDqlgmjTPINhFiGlzwRN4DBiPhk3xLfFsOyHsaC0puX+7oh7xpKjbndKookH4rwoLXKYaXpK6azNd3D540/NFKjNbaZ4EYOob2F7rNOC3SW2FT0Ay7HOsoPZkR3zQ++Jqfv9I/Ric1CH09Q9C8KhONpIKPJ1HgDlddwxcvbfLJ94pfYvZ0Ebv3zVHykvLBQxLnlf9GruhlWXuaibc0Ja2atMP+PKXuSdfr4+Bn0FInQZRc3CVLshlj/RkjkV/cs2gCdGG7vrOlOuWfoZ2atbI5zMJCrxO3YGUMubXmg4DxeOt+NPxtZ7LQ2nqm+AObEJvqm8BI6/xxnezO5d8/v5f30j93sOH+anyVYKMduEdeVAWywTIDvNvXNCIqWYgYCFdI3MBJiDOW0d9edBeGtp/F543lSou/DUqHmXJcV/AcC1khiLo4mJYIBcYADEkgKVMGJ9w="
  file: 
  - dist/pnc_linux_arm.tar.gz
  - dist/pnc_linux_arm64.tar.gz
  - dist/pnc_linux_386.tar.gz
  - dist/pnc_linux_amd64.tar.gz
  - dist/pnc_windows_386.zip
  - dist/pnc_windows_amd64.zip
  skip_cleanup: true
  on:
    tags: true